stages:
  - build

build:
  stage: build
  tags:
    - docker
  image: 
    name: gitlab-registry.cern.ch/bnl-atlas/larphase2/fetb2/fetb2os/petalinuxdocker:2020p2
  artifacts:
    paths:
      - images/linux
    expire_in: 1 hour
  script:
    - petalinux-build
    - source package.sh
  
